# Diabetes Health Indicators - ML Project
## A complete Machine Learning pipeline for Binary Classification, Multiclass Classification, and Regression

## Step 1: Importing the Libraries

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Step 2: Loading & Inspecting the Data

In [4]:
df = pd.read_csv("../data/raw/diabetes_dataset.csv")

In [6]:
df.head()

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
0,58,Male,Asian,Highschool,Lower-Middle,Employed,Never,0,215,5.7,...,41,160,145,136,236,6.36,8.18,29.6,Type 2,1
1,48,Female,White,Highschool,Middle,Employed,Former,1,143,6.7,...,55,50,30,93,150,2.00,5.63,23.0,No Diabetes,0
2,60,Male,Hispanic,Highschool,Middle,Unemployed,Never,1,57,6.4,...,66,99,36,118,195,5.07,7.51,44.7,Type 2,1
3,74,Female,Black,Highschool,Low,Retired,Never,0,49,3.4,...,50,79,140,139,253,5.28,9.03,38.2,Type 2,1
4,46,Male,White,Graduate,Middle,Retired,Never,1,109,7.2,...,52,125,160,137,184,12.74,7.20,23.5,Type 2,1

In [18]:
# Data Loaded Successfully

print(f'Shape of Data : \n Rows :  {df.shape[0]} \n Columns : {df.shape[1]}')

Shape of Data :
 Rows :  100000
 Columns : 31

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 31 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   age                                 100000 non-null  int64
 1   gender                              100000 non-null  object
 2   ethnicity                           100000 non-null  object
 3   education_level                     100000 non-null  object
 4   income_level                        100000 non-null  object
 5   employment_status                   100000 non-null  object
 6   smoking_status                      100000 non-null  object
 7   alcohol_consumption_per_week        100000 non-null  int64
 8   physical_activity_minutes_per_week  100000 non-null  int64
 9   diet_score                          100000 non-null  float64
 10  sleep_hours_per_day                 100000 non-null  float64
 11  screen_time_hours_per_day           100000 non-null  float64
 12  family_history_diabetes             100000 non-null  int64
 13  hypertension_history                100000 non-null  int64
 14  cardiovascular_history              100000 non-null  int64
 15  bmi                                 100000 non-null  float64
 16  waist_to_hip_ratio                  100000 non-null  float64
 17  systolic_bp                         100000 non-null  int64
 18  diastolic_bp                        100000 non-null  int64
 19  heart_rate                          100000 non-null  int64
 20  cholesterol_total                   100000 non-null  int64
 21  hdl_cholesterol                     100000 non-null  int64
 22  ldl_cholesterol                     100000 non-null  int64
 23  triglycerides                       100000 non-null  int64
 24  glucose_fasting                     100000 non-null  int64
 25  glucose_postprandial                100000 non-null  int64
 26  insulin_level                       100000 non-null  float64
 27  hba1c                               100000 non-null  float64
 28  diabetes_risk_score                 100000 non-null  float64
 29  diabetes_stage                      100000 non-null  object
 30  diagnosed_diabetes                  100000 non-null  int64
dtypes: float64(8), int64(16), object(7)
memory usage: 23.7+ MB

In [21]:
df.isnull().sum()

age                                   0
gender                                0
ethnicity                             0
education_level                       0
income_level                          0
employment_status                     0
smoking_status                        0
alcohol_consumption_per_week          0
physical_activity_minutes_per_week    0
diet_score                            0
sleep_hours_per_day                   0
screen_time_hours_per_day             0
family_history_diabetes               0
hypertension_history                  0
cardiovascular_history                0
bmi                                   0
waist_to_hip_ratio                    0
systolic_bp                           0
diastolic_bp                          0
heart_rate                            0
cholesterol_total                     0
hdl_cholesterol                       0
ldl_cholesterol                       0
triglycerides                         0
glucose_fasting                       0
glucose_postprandial                  0
insulin_level                         0
hba1c                                 0
diabetes_risk_score                   0
diabetes_stage                        0
diagnosed_diabetes                    0
dtype: int64

In [24]:
df.describe()

,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,family_history_diabetes,hypertension_history,cardiovascular_history,bmi,...,cholesterol_total,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diagnosed_diabetes
count,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50.12041,2.003670,118.911640,5.994787,6.997818,5.996468,0.219410,0.250800,0.079200,25.612653,...,185.978110,54.042790,103.000430,121.462650,111.11712,160.035050,9.061242,6.520776,30.222362,0.599980
std,15.60460,1.417779,84.409662,1.780954,1.094622,2.468406,0.413849,0.433476,0.270052,3.586705,...,32.013005,10.267374,33.390256,43.372619,13.59561,30.935472,4.954060,0.813921,9.061505,0.489904
min,18.00000,0.000000,0.000000,0.000000,3.000000,0.500000,0.000000,0.000000,0.000000,15.000000,...,100.000000,20.000000,50.000000,30.000000,60.00000,70.000000,2.000000,4.000000,2.700000,0.000000
25%,39.00000,1.000000,57.000000,4.800000,6.300000,4.300000,0.000000,0.000000,0.000000,23.200000,...,164.000000,47.000000,78.000000,91.000000,102.00000,139.000000,5.090000,5.970000,23.800000,0.000000
50%,50.00000,2.000000,100.000000,6.000000,7.000000,6.000000,0.000000,0.000000,0.000000,25.600000,...,186.000000,54.000000,102.000000,121.000000,111.00000,160.000000,8.790000,6.520000,29.000000,1.000000
75%,61.00000,3.000000,160.000000,7.200000,7.700000,7.700000,0.000000,1.000000,0.000000,28.000000,...,208.000000,61.000000,126.000000,151.000000,120.00000,181.000000,12.450000,7.070000,35.600000,1.000000
max,90.00000,10.000000,833.000000,10.000000,10.000000,16.800000,1.000000,1.000000,1.000000,39.200000,...,318.000000,98.000000,263.000000,344.000000,172.00000,287.000000,32.220000,9.800000,67.200000,1.000000

In [27]:
df.duplicated().sum()

np.int64(0)

In [33]:
# Inspect target columns for each ML task
print("=== Binary Classification Target ===")
print(df['diagnosed_diabetes'].value_counts())

print("\n=== Multiclass Classification Target ===")
print(df['diabetes_stage'].value_counts())

print("\n=== Regression Target ===") 
print(df['diabetes_risk_score'].describe())

=== Binary Classification Target ===
diagnosed_diabetes
1    59998
0    40002
Name: count, dtype: int64

=== Multiclass Classification Target ===
diabetes_stage
Type 2          59774
Pre-Diabetes    31845
No Diabetes      7981
Gestational       278
Type 1            122
Name: count, dtype: int64

=== Regression Target ===
count    100000.000000
mean         30.222362
std           9.061505
min           2.700000
25%          23.800000
50%          29.000000
75%          35.600000
max          67.200000
Name: diabetes_risk_score, dtype: float64

## Step 3: Data Preprocessing
In this step we handle missing values, encode categorical variables, and normalize numerical features.

In [37]:
df.isnull().sum().sum()

np.int64(0)

In [51]:
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
numerical_cols  = df.select_dtypes(include=['int', 'float']).columns.tolist()

In [53]:
from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

le = LabelEncoder()

for cols in categorical_cols : 
    df_encoded[cols] = le.fit_transform(df_encoded[cols])

In [56]:
df_encoded.head()

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
0,58,1,0,1,2,0,2,0,215,5.7,...,41,160,145,136,236,6.36,8.18,29.6,4,1
1,48,0,4,1,3,0,1,1,143,6.7,...,55,50,30,93,150,2.00,5.63,23.0,1,0
2,60,1,2,1,3,3,2,1,57,6.4,...,66,99,36,118,195,5.07,7.51,44.7,4,1
3,74,0,1,1,1,1,2,0,49,3.4,...,50,79,140,139,253,5.28,9.03,38.2,4,1
4,46,1,4,0,3,1,2,1,109,7.2,...,52,125,160,137,184,12.74,7.20,23.5,4,1

In [59]:
# Define target columns
target_binary = 'diagnosed_diabetes'
target_multiclass = 'diabetes_stage'
target_regression = 'diabetes_risk_score'

feature_cols = [col for col in df_encoded.columns if col not in [target_binary, target_multiclass, target_regression]]

X = df_encoded[feature_cols]

# Targets
y_binary = df_encoded[target_binary]
y_multiclass = df_encoded[target_multiclass]
y_regression = df_encoded[target_regression]

print("✅ Features and targets separated!")
print(f"Features shape: {X.shape}")
print(f"Binary target shape: {y_binary.shape}")
print(f"Multiclass target shape: {y_multiclass.shape}")
print(f"Regression target shape: {y_regression.shape}")

✅ Features and targets separated!
Features shape: (100000, 28)
Binary target shape: (100000,)
Multiclass target shape: (100000,)
Regression target shape: (100000,)

In [60]:
from sklearn.preprocessing import StandardScaler

# Apply StandardScaler to normalize numerical features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Convert back to DataFrame
X_scaled = pd.DataFrame(X_scaled, columns=feature_cols)

print("✅ Features standardized successfully!")
X_scaled.head()

✅ Features standardized successfully!

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,diastolic_bp,heart_rate,cholesterol_total,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c
0,0.504956,0.895204,-1.700046,-0.000070,-0.448732,-0.681646,0.752904,-1.413253,1.138363,-0.165523,...,0.337328,-0.195041,1.656269,-1.270320,1.707081,0.542680,1.830223,2.455606,-0.545261,2.038566
1,-0.135884,-0.961951,0.984304,-0.000070,0.447835,-0.681646,-0.494390,-0.707921,0.285376,0.395977,...,0.093551,-0.314489,-2.185938,0.093229,-1.587310,-2.108775,-1.332578,-0.324388,-1.425352,-1.094431
2,0.633124,0.895204,-0.357871,-0.000070,0.447835,2.247772,0.752904,-0.707921,-0.733470,0.227527,...,-0.272115,0.521641,0.844095,1.164589,-0.119809,-1.970438,0.506260,1.130260,-0.805655,1.215387
3,1.530299,-0.961951,-1.028958,-0.000070,-1.345299,0.294826,0.752904,-1.413253,-0.828246,-1.456972,...,2.165658,-0.195041,-0.467878,-0.393753,-0.718789,0.427400,2.050884,3.005140,-0.763265,3.082899
4,-0.264052,0.895204,0.984304,-0.999945,0.447835,0.294826,0.752904,-0.707921,-0.117424,0.676727,...,-1.003447,-0.314489,0.750383,-0.198960,0.658865,0.888522,1.903777,0.774679,0.742578,0.834512

In [61]:
# Save processed data to data/processed/
df_encoded.to_csv("../data/processed/diabetes_processed.csv", index=False)

print("✅ Processed dataset saved to data/processed/diabetes_processed.csv")

✅ Processed dataset saved to data/processed/diabetes_processed.csv